FROM golang:alpine as base

WORKDIR /go

RUN apk add --no-cache git ca-certificates && update-ca-certificates

RUN apk update && apk add bash && apk add --no-cache gcc musl-dev && apk add --no-cache git

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o ./app cmd/main.go

FROM scratch

COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY --from=base /go/app ./

ENTRYPOINT ["./app"]
