FROM node:12-alpine AS base
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json ./
RUN npm i --only=prod 

FROM node:12-alpine AS build
WORKDIR /app
COPY . .
COPY --from=base /app/node_modules ./node_modules
RUN npm run build

FROM node:12-alpine
WORKDIR /app
ENV NODE_ENV production
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001
RUN chown -R nextjs:nodejs /app/.next
USER nextjs
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
